/*DO NOT EDIT THIS FILE - it is machine generated*/

package com.badlogic.gdx.backends.iosrobovm;

import java.io.File;

import org.robovm.apple.coregraphics.CGRect;
import org.robovm.apple.foundation.NSMutableDictionary;
import org.robovm.apple.foundation.NSObject;
import org.robovm.apple.foundation.NSProcessInfo;
import org.robovm.apple.foundation.NSString;
import org.robovm.apple.uikit.UIApplication;
import org.robovm.apple.uikit.UIApplicationDelegateAdapter;
import org.robovm.apple.uikit.UIApplicationLaunchOptions;
import org.robovm.apple.uikit.UIDevice;
import org.robovm.apple.uikit.UIScene;
import org.robovm.apple.uikit.UISceneConfiguration;
import org.robovm.apple.uikit.UISceneConnectionOptions;
import org.robovm.apple.uikit.UISceneSession;
import org.robovm.apple.uikit.UIStatusBarManager;
import org.robovm.apple.uikit.UIUserInterfaceIdiom;
import org.robovm.apple.uikit.UIPasteboard;
import org.robovm.apple.uikit.UIScreen;
import org.robovm.apple.uikit.UIViewController;
import org.robovm.apple.uikit.UIWindow;
import org.robovm.apple.uikit.UIWindowScene;
import org.robovm.apple.uikit.UIWindowSceneDelegateAdapter;
import org.robovm.objc.annotation.CustomClass;
import org.robovm.rt.bro.Bro;
import org.robovm.rt.bro.annotation.ForceLinkClass;

import com.badlogic.gdx.Application;
import com.badlogic.gdx.ApplicationListener;
import com.badlogic.gdx.ApplicationLogger;
import com.badlogic.gdx.Audio;
import com.badlogic.gdx.Files;
import com.badlogic.gdx.Gdx;
import com.badlogic.gdx.Graphics;
import com.badlogic.gdx.Input;
import com.badlogic.gdx.LifecycleListener;
import com.badlogic.gdx.Net;
import com.badlogic.gdx.Preferences;
import com.badlogic.gdx.backends.iosrobovm.objectal.OALIOSAudio;
import com.badlogic.gdx.utils.Array;
import com.badlogic.gdx.utils.Clipboard;

/**
 * libGDX 1.14.2 IOSApplication with the window setup moved to a single UIWindowScene.
 * The public and package-visible API is intentionally kept compatible with the
 * upstream backend so the other classes in the original JAR can be reused.
 */
public class IOSApplication implements Application {

	@ForceLinkClass(SceneDelegate.class)
	public static abstract class Delegate extends UIApplicationDelegateAdapter {

		private IOSApplication app;

		protected abstract IOSApplication createApplication ();

		@Override
		public boolean didFinishLaunching (UIApplication application, UIApplicationLaunchOptions launchOptions) {
			// Prevent this from being GCed until the ObjC UIApplication is deallocated
			application.addStrongRef(this);
			this.app = createApplication();
			return app.didFinishLaunching(application, launchOptions);
		}

		@Override
		public UISceneConfiguration getConfigurationForConnectingSceneSession (UIApplication application,
			UISceneSession connectingSceneSession, UISceneConnectionOptions options) {
			UISceneConfiguration configuration = new UISceneConfiguration("Default Configuration",
				connectingSceneSession.getRole());
			configuration.setSceneClass(UIWindowScene.class);
			configuration.setDelegateClass(SceneDelegate.class);
			return configuration;
		}

		@Override
		public void didBecomeActive (UIApplication application) {
			app.didBecomeActive(application);
		}

		@Override
		public void willEnterForeground (UIApplication application) {
			app.willEnterForeground(application);
		}

		@Override
		public void willResignActive (UIApplication application) {
			app.willResignActive(application);
		}

		@Override
		public void didEnterBackground (UIApplication application) {
			app.didEnterBackground();
		}

		@Override
		public void willTerminate (UIApplication application) {
			app.willTerminate(application);
		}
	}

	@CustomClass(value = "UncivSceneDelegate", preload = true)
	public static final class SceneDelegate extends UIWindowSceneDelegateAdapter {

		@Override
		public void willConnect (UIScene scene, UISceneSession session, UISceneConnectionOptions options) {
			if (!(scene instanceof UIWindowScene)) return;
			// UIScene.delegate is not an ownership boundary RoboVM can infer.
			scene.addStrongRef(this);
			setWindow(requirePreparedApplication().connectScene((UIWindowScene)scene));
		}

		@Override
		public void sceneDidBecomeActive (UIScene scene) {
			IOSApplication app = preparedApplication;
			if (app != null) app.didBecomeActive(app.uiApp);
		}

		@Override
		public void sceneWillResignActive (UIScene scene) {
			IOSApplication app = preparedApplication;
			if (app != null) app.willResignActive(app.uiApp);
		}

		@Override
		public void sceneWillEnterForeground (UIScene scene) {
			IOSApplication app = preparedApplication;
			if (app != null) app.willEnterForeground(app.uiApp);
		}

		@Override
		public void sceneDidEnterBackground (UIScene scene) {
			IOSApplication app = preparedApplication;
			if (app != null) app.didEnterBackground();
		}
	}

	static final boolean IS_METALANGLE = true;

	private static IOSApplication preparedApplication;

	UIApplication uiApp;

	UIWindow uiWindow;

	ApplicationListener listener;

	IOSViewControllerListener viewControllerListener;

	IOSApplicationConfiguration config;

	IOSGraphics graphics;

	IOSAudio audio;

	Files files;

	IOSInput input;

	IOSNet net;

	int logLevel = Application.LOG_DEBUG;

	ApplicationLogger applicationLogger;

	/** The display scale factor (1.0f for normal; 2.0f to use retina coordinates/dimensions). */
	float pixelsPerPoint;

	private IOSScreenBounds lastScreenBounds = null;

	private boolean initialized;

	private boolean active;

	private boolean foreground;

	private boolean terminated;

	Array<Runnable> runnables = new Array<Runnable>();

	Array<Runnable> executedRunnables = new Array<Runnable>();

	Array<LifecycleListener> lifecycleListeners = new Array<LifecycleListener>();

	public IOSApplication (ApplicationListener listener, IOSApplicationConfiguration config) {
		this.listener = listener;
		this.config = config;
	}

	private static IOSApplication requirePreparedApplication () {
		if (preparedApplication == null)
			throw new IllegalStateException("UIScene connected before IOSApplication.Delegate finished launching");
		return preparedApplication;
	}

	final boolean didFinishLaunching (UIApplication uiApp, UIApplicationLaunchOptions options) {
		setApplicationLogger(new IOSApplicationLogger());
		Gdx.app = this;
		this.uiApp = uiApp;
		preparedApplication = this;
		// enable or disable screen dimming
		uiApp.setIdleTimerDisabled(config.preventScreenDimming);
		Gdx.app.debug("IOSApplication", "iOS version: " + UIDevice.getCurrentDevice().getSystemVersion());
		Gdx.app.debug("IOSApplication", "Running in " + (Bro.IS_64BIT ? "64-bit" : "32-bit") + " mode");
		return true;
	}

	private synchronized UIWindow connectScene (UIWindowScene windowScene) {
		if (initialized) {
			if (uiWindow.getWindowScene() != windowScene) uiWindow.setWindowScene(windowScene);
			lastScreenBounds = null;
			graphics.updateSafeInsets();
			uiWindow.makeKeyAndVisible();
			return uiWindow;
		}

		pixelsPerPoint = (float)windowScene.getScreen().getNativeScale();
		Gdx.app.debug("IOSApplication", "Pixels per point: " + pixelsPerPoint);
		this.uiWindow = new UIWindow(windowScene);
		uiApp.getDelegate().setWindow(uiWindow);

		// setup libgdx
		this.input = createInput();
		this.graphics = createGraphics();
		Gdx.gl = Gdx.gl20 = graphics.gl20;
		Gdx.gl30 = graphics.gl30;
		this.files = createFiles();
		this.audio = createAudio(config);
		this.net = new IOSNet(this, config);
		Gdx.files = this.files;
		Gdx.graphics = this.graphics;
		Gdx.audio = this.audio;
		Gdx.input = this.input;
		Gdx.net = this.net;
		this.input.setupPeripherals();
		this.uiWindow.setRootViewController(this.graphics.viewController);
		this.uiWindow.makeKeyAndVisible();
		this.graphics.updateSafeInsets();
		Gdx.app.debug("IOSApplication", "created");
		// Trigger first render, special case that is caught and returned
		this.graphics.view.display();
		listener.create();
		listener.resize(this.graphics.getWidth(), this.graphics.getHeight());
		// make sure the OpenGL view has contents before displaying it
		this.graphics.view.display();
		initialized = true;
		return uiWindow;
	}

	protected Files createFiles () {
		return new IOSFiles();
	}

	protected IOSAudio createAudio (IOSApplicationConfiguration config) {
		if (config.useAudio)
			return new OALIOSAudio(config);
		else
			return new DisabledIOSAudio();
	}

	protected IOSGraphics createGraphics () {
		return new IOSGraphics(this, config, input, config.useGL30);
	}

	protected IOSUIViewController createUIViewController (IOSGraphics graphics) {
		return new IOSUIViewController(this, graphics);
	}

	protected IOSInput createInput () {
		return new DefaultIOSInput(this);
	}

	/** Returns device ppi using a best guess approach when device is unknown. Overwrite to customize strategy. */
	protected int guessUnknownPpi () {
		int ppi;
		if (UIDevice.getCurrentDevice().getUserInterfaceIdiom() == UIUserInterfaceIdiom.Pad)
			ppi = 132 * (int)pixelsPerPoint;
		else
			ppi = 164 * (int)pixelsPerPoint;
		error("IOSApplication", "Device PPI unknown. PPI value has been guessed to " + ppi + " but may be wrong");
		return ppi;
	}

	/** Return the UI view controller of IOSApplication
	 * @return the view controller of IOSApplication */
	public UIViewController getUIViewController () {
		return graphics.viewController;
	}

	/** Return the UI Window of IOSApplication
	 * @return the window */
	public UIWindow getUIWindow () {
		return uiWindow;
	}

	/** @see IOSScreenBounds for detailed explanation
	 * @return logical dimensions of space we draw to, adjusted for device orientation */
	protected IOSScreenBounds computeBounds () {
		CGRect screenBounds = uiWindow.getBounds();
		UIWindowScene windowScene = uiWindow.getWindowScene();
		UIStatusBarManager statusBarManager = windowScene == null ? null : windowScene.getStatusBarManager();
		CGRect statusBarFrame = statusBarManager == null ? uiApp.getStatusBarFrame() : statusBarManager.getStatusBarFrame();
		double statusBarHeight = statusBarFrame.getHeight();
		double screenWidth = screenBounds.getWidth();
		double screenHeight = screenBounds.getHeight();
		if (statusBarHeight != 0.0) {
			debug("IOSApplication", "Status bar is visible (height = " + statusBarHeight + ")");
			screenHeight -= statusBarHeight;
		} else {
			debug("IOSApplication", "Status bar is not visible");
		}
		final int offsetX = 0;
		final int offsetY = (int)Math.round(statusBarHeight);
		final int width = (int)Math.round(screenWidth);
		final int height = (int)Math.round(screenHeight);
		final int backBufferWidth = (int)Math.round(screenWidth * pixelsPerPoint);
		final int backBufferHeight = (int)Math.round(screenHeight * pixelsPerPoint);
		debug("IOSApplication", "Computed bounds are x=" + offsetX + " y=" + offsetY + " w=" + width + " h=" + height + " bbW= "
			+ backBufferWidth + " bbH= " + backBufferHeight);
		return lastScreenBounds = new IOSScreenBounds(offsetX, offsetY, width, height, backBufferWidth, backBufferHeight);
	}

	/** @return area of screen in UIKit points on which libGDX draws, with 0,0 being upper left corner */
	public IOSScreenBounds getScreenBounds () {
		if (lastScreenBounds == null)
			return computeBounds();
		else
			return lastScreenBounds;
	}

	final void didBecomeActive (UIApplication uiApp) {
		if (!initialized || terminated || active) return;
		active = true;
		foreground = true;
		Gdx.app.debug("IOSApplication", "resumed");
		audio.didBecomeActive();
		graphics.makeCurrent();
		graphics.resume();
	}

	final void willEnterForeground (UIApplication uiApp) {
		if (!initialized || terminated || foreground) return;
		foreground = true;
		audio.willEnterForeground();
	}

	final void willResignActive (UIApplication uiApp) {
		if (!initialized || terminated || !active) return;
		active = false;
		Gdx.app.debug("IOSApplication", "paused");
		audio.willResignActive();
		graphics.makeCurrent();
		graphics.pause();
		Gdx.gl.glFinish();
	}

	final void didEnterBackground () {
		foreground = false;
	}

	final void willTerminate (UIApplication uiApp) {
		if (!initialized || terminated) return;
		terminated = true;
		Gdx.app.debug("IOSApplication", "disposed");
		audio.dispose();
		graphics.makeCurrent();
		Array<LifecycleListener> listeners = lifecycleListeners;
		synchronized (listeners) {
			for (LifecycleListener listener : listeners) {
				listener.pause();
			}
		}
		listener.dispose();
		Gdx.gl.glFinish();
		if (preparedApplication == this) preparedApplication = null;
	}

	@Override
	public ApplicationListener getApplicationListener () {
		return listener;
	}

	@Override
	public Graphics getGraphics () {
		return graphics;
	}

	@Override
	public Audio getAudio () {
		return audio;
	}

	@Override
	public Input getInput () {
		return input;
	}

	@Override
	public Files getFiles () {
		return files;
	}

	@Override
	public Net getNet () {
		return net;
	}

	@Override
	public void debug (String tag, String message) {
		if (logLevel >= LOG_DEBUG) getApplicationLogger().debug(tag, message);
	}

	@Override
	public void debug (String tag, String message, Throwable exception) {
		if (logLevel >= LOG_DEBUG) getApplicationLogger().debug(tag, message, exception);
	}

	@Override
	public void log (String tag, String message) {
		if (logLevel >= LOG_INFO) getApplicationLogger().log(tag, message);
	}

	@Override
	public void log (String tag, String message, Throwable exception) {
		if (logLevel >= LOG_INFO) getApplicationLogger().log(tag, message, exception);
	}

	@Override
	public void error (String tag, String message) {
		if (logLevel >= LOG_ERROR) getApplicationLogger().error(tag, message);
	}

	@Override
	public void error (String tag, String message, Throwable exception) {
		if (logLevel >= LOG_ERROR) getApplicationLogger().error(tag, message, exception);
	}

	@Override
	public void setLogLevel (int logLevel) {
		this.logLevel = logLevel;
	}

	@Override
	public int getLogLevel () {
		return logLevel;
	}

	@Override
	public void setApplicationLogger (ApplicationLogger applicationLogger) {
		this.applicationLogger = applicationLogger;
	}

	@Override
	public ApplicationLogger getApplicationLogger () {
		return applicationLogger;
	}

	@Override
	public ApplicationType getType () {
		return ApplicationType.iOS;
	}

	@Override
	public int getVersion () {
		return (int)NSProcessInfo.getSharedProcessInfo().getOperatingSystemVersion().getMajorVersion();
	}

	@Override
	public long getJavaHeap () {
		return Runtime.getRuntime().totalMemory() - Runtime.getRuntime().freeMemory();
	}

	@Override
	public long getNativeHeap () {
		return getJavaHeap();
	}

	@Override
	public Preferences getPreferences (String name) {
		File libraryPath = new File(System.getenv("HOME"), "Library");
		File finalPath = new File(libraryPath, name + ".plist");
		@SuppressWarnings("unchecked")
		NSMutableDictionary<NSString, NSObject> nsDictionary = (NSMutableDictionary<NSString, NSObject>)NSMutableDictionary
			.read(finalPath);
		// if it fails to get an existing dictionary, create a new one.
		if (nsDictionary == null) {
			nsDictionary = new NSMutableDictionary<NSString, NSObject>();
			nsDictionary.write(finalPath, false);
		}
		return new IOSPreferences(nsDictionary, finalPath.getAbsolutePath());
	}

	@Override
	public void postRunnable (Runnable runnable) {
		synchronized (runnables) {
			runnables.add(runnable);
			Gdx.graphics.requestRendering();
		}
	}

	public void processRunnables () {
		synchronized (runnables) {
			executedRunnables.clear();
			executedRunnables.addAll(runnables);
			runnables.clear();
		}
		for (int i = 0; i < executedRunnables.size; i++) {
			executedRunnables.get(i).run();
		}
	}

	@Override
	public void exit () {
		System.exit(0);
	}

	@Override
	public Clipboard getClipboard () {
		return new Clipboard() {

			@Override
			public void setContents (String content) {
				UIPasteboard.getGeneralPasteboard().setString(content);
			}

			@Override
			public boolean hasContents () {
				return UIPasteboard.getGeneralPasteboard().hasStrings();
			}

			@Override
			public String getContents () {
				return UIPasteboard.getGeneralPasteboard().getString();
			}
		};
	}

	@Override
	public void addLifecycleListener (LifecycleListener listener) {
		synchronized (lifecycleListeners) {
			lifecycleListeners.add(listener);
		}
	}

	@Override
	public void removeLifecycleListener (LifecycleListener listener) {
		synchronized (lifecycleListeners) {
			lifecycleListeners.removeValue(listener, true);
		}
	}

	/** Add a listener to handle events from the libGDX root view controller
	 * @param listener The {#link IOSViewControllerListener} to add */
	public void addViewControllerListener (IOSViewControllerListener listener) {
		viewControllerListener = listener;
	}
}
